Document: editobj2
Title: Debian editobj2 Manual
Author: <insert document author here>
Abstract: This manual describes what editobj2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/editobj2/editobj2.sgml.gz

Format: postscript
Files: /usr/share/doc/editobj2/editobj2.ps.gz

Format: text
Files: /usr/share/doc/editobj2/editobj2.text.gz

Format: HTML
Index: /usr/share/doc/editobj2/html/index.html
Files: /usr/share/doc/editobj2/html/*.html
